// ---------------------------------------------------------------------------
// Demo place directory for the Environment Hub recommendation system.
// ALL entries are illustrative SAMPLE records for demonstration only.
// They are not verified real-world facilities: no real phone numbers, ratings
// or opening hours are invented from official registries.
// ---------------------------------------------------------------------------

import type { SourceInfo } from "./locations";

export const PLACES_DISCLAIMER =
  "Place records shown here are illustrative sample data for this demo. Details are not verified against official facility registries — always confirm before travelling, and call emergency services directly in an emergency.";

export type PlaceCategory =
  | "healthcare"
  | "emergency"
  | "pharmacy"
  | "education"
  | "tourism"
  | "recreation"
  | "entertainment"
  | "restaurant"
  | "shopping"
  | "religious"
  | "government"
  | "transportation"
  | "accommodation"
  | "cultural"
  | "outdoor"
  | "business";

export const PLACE_CATEGORY_LABELS: Record<PlaceCategory, string> = {
  healthcare: "Healthcare",
  emergency: "Emergency services",
  pharmacy: "Pharmacy",
  education: "Education",
  tourism: "Tourism",
  recreation: "Recreation",
  entertainment: "Entertainment",
  restaurant: "Restaurants & food",
  shopping: "Shopping",
  religious: "Religious places",
  government: "Government services",
  transportation: "Transportation",
  accommodation: "Accommodation",
  cultural: "Cultural & historical",
  outdoor: "Outdoor activities",
  business: "Business services",
};

export interface OpeningHours {
  /** Human readable summary, e.g. "Mon–Sat 08:00–18:00". */
  summary: string;
  /** 24h open range used for a coarse "open now" estimate. null = 24 hours. */
  opens: number | null;
  closes: number | null;
  /** Days of week the place opens: 0 = Sunday. */
  days: number[];
}

export interface Place {
  id: string;
  name: string;
  category: PlaceCategory;
  subtype: string;
  ownership: "Public" | "Private" | "Community";
  locationSlug: string;
  area: string;
  address: string;
  coords: [number, number];
  description: string;
  services: string[];
  /** Free-text tags used by the intent matcher (needs, occasions, audiences). */
  tags: string[];
  hours: OpeningHours;
  phone: string | null;
  website: string | null;
  rating: { value: number; count: number; source: string } | null;
  priceLevel: 1 | 2 | 3 | 4 | null;
  accessibility: string[];
  emergency: boolean;
  source: SourceInfo;
  verified: string;
}

const DIR = (date: string): SourceInfo => ({
  name: "Sample place directory (demo dataset)",
  date,
});

const ALL_WEEK = [0, 1, 2, 3, 4, 5, 6];
const MON_SAT = [1, 2, 3, 4, 5, 6];

const H = (summary: string, opens: number | null, closes: number | null, days = ALL_WEEK): OpeningHours => ({
  summary,
  opens,
  closes,
  days,
});

const ALWAYS = H("Open 24 hours, every day", null, null, ALL_WEEK);

type Seed = Omit<Place, "id" | "source" | "verified">;

function build(seeds: Seed[]): Place[] {
  return seeds.map((s, i) => ({
    ...s,
    id: `${s.locationSlug}-${s.category}-${i}`,
    source: DIR("Aug 2026"),
    verified: "Sample record — not verified against an official registry",
  }));
}

const SEEDS: Seed[] = [
  // ------------------------------------------------------------ Wuse 2, Abuja
  {
    name: "Wuse District General Hospital (sample)",
    category: "healthcare",
    subtype: "General hospital",
    ownership: "Public",
    locationSlug: "wuse-2-abuja",
    area: "Wuse 2",
    address: "Aminu Kano Crescent, Wuse 2, Abuja",
    coords: [9.0781, 7.4652],
    description:
      "Sample general hospital record with a 24-hour accident & emergency unit, general outpatient department and an on-site laboratory.",
    services: ["Accident & emergency", "General outpatient", "Laboratory & diagnostics", "Maternity", "Malaria & fever testing", "Inpatient beds"],
    tags: ["hospital", "malaria", "fever", "typhoid", "treatment", "emergency", "doctor", "illness", "injury", "sick"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: { value: 4.1, count: 128, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Step-free entrance", "Ambulance bay"],
    emergency: true,
  },
  {
    name: "Crescent Medical Clinic (sample)",
    category: "healthcare",
    subtype: "Private clinic",
    ownership: "Private",
    locationSlug: "wuse-2-abuja",
    area: "Wuse 2",
    address: "Ademola Adetokunbo Crescent, Wuse 2, Abuja",
    coords: [9.0722, 7.4731],
    description:
      "Sample private clinic record offering general consultation, rapid malaria testing and family medicine appointments.",
    services: ["General consultation", "Rapid malaria testing", "Family medicine", "Vaccinations", "Minor procedures"],
    tags: ["clinic", "malaria", "fever", "consultation", "treatment", "children", "family", "sick"],
    hours: H("Mon–Sat 08:00–20:00", 8, 20, MON_SAT),
    phone: null,
    website: null,
    rating: { value: 4.4, count: 76, source: "Sample review dataset" },
    priceLevel: 3,
    accessibility: ["Step-free entrance"],
    emergency: false,
  },
  {
    name: "Wuse 2 Community Pharmacy (sample)",
    category: "pharmacy",
    subtype: "Retail pharmacy",
    ownership: "Private",
    locationSlug: "wuse-2-abuja",
    area: "Wuse 2",
    address: "Gana Street, Wuse 2, Abuja",
    coords: [9.0803, 7.4705],
    description: "Sample pharmacy record with prescription dispensing and over-the-counter medicines.",
    services: ["Prescription dispensing", "Over-the-counter medicines", "Anti-malarials", "Blood pressure check"],
    tags: ["pharmacy", "chemist", "medicine", "drugs", "malaria", "prescription"],
    hours: H("Mon–Sun 07:00–22:00", 7, 22),
    phone: null,
    website: null,
    rating: { value: 4.2, count: 54, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Step-free entrance"],
    emergency: false,
  },
  {
    name: "Wuse Division Police Station (sample)",
    category: "emergency",
    subtype: "Police station",
    ownership: "Public",
    locationSlug: "wuse-2-abuja",
    area: "Wuse 2",
    address: "Off Adetokunbo Ademola Crescent, Wuse 2, Abuja",
    coords: [9.0748, 7.4772],
    description: "Sample police division record providing 24-hour incident reporting and patrol response.",
    services: ["Incident reporting", "Patrol response", "Lost property"],
    tags: ["police", "safety", "emergency", "report", "crime", "help"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: null,
    priceLevel: null,
    accessibility: ["Step-free entrance"],
    emergency: true,
  },
  {
    name: "Central Park & Gardens (sample)",
    category: "outdoor",
    subtype: "Public park",
    ownership: "Public",
    locationSlug: "wuse-2-abuja",
    area: "Wuse 2",
    address: "Off Shehu Shagari Way, Abuja",
    coords: [9.0691, 7.4823],
    description:
      "Sample landscaped park record with walking paths, shaded lawns, a children's play area and weekend events.",
    services: ["Walking paths", "Children's play area", "Picnic lawns", "Weekend events", "Food kiosks"],
    tags: ["park", "relax", "peaceful", "quiet", "holiday", "family", "children", "picnic", "outdoor", "weekend", "nature", "fresh air"],
    hours: H("Every day 06:00–20:00", 6, 20),
    phone: null,
    website: null,
    rating: { value: 4.5, count: 310, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Paved paths", "Accessible toilets"],
    emergency: false,
  },
  {
    name: "Capital Family Fun Centre (sample)",
    category: "entertainment",
    subtype: "Family entertainment centre",
    ownership: "Private",
    locationSlug: "wuse-2-abuja",
    area: "Wuse 2",
    address: "Ahmadu Bello Way, Wuse 2, Abuja",
    coords: [9.0669, 7.4667],
    description:
      "Sample indoor entertainment record with arcade games, a cinema screen and a children's play zone.",
    services: ["Arcade games", "Cinema", "Children's play zone", "Birthday packages", "Café"],
    tags: ["entertainment", "children", "kids", "family", "holiday", "fun", "cinema", "weekend", "games"],
    hours: H("Every day 10:00–22:00", 10, 22),
    phone: null,
    website: null,
    rating: { value: 4.3, count: 189, source: "Sample review dataset" },
    priceLevel: 3,
    accessibility: ["Lift access", "Family restroom"],
    emergency: false,
  },
  {
    name: "Riverside Family Restaurant (sample)",
    category: "restaurant",
    subtype: "Family restaurant",
    ownership: "Private",
    locationSlug: "wuse-2-abuja",
    area: "Wuse 2",
    address: "Aminu Kano Crescent, Wuse 2, Abuja",
    coords: [9.0774, 7.4694],
    description:
      "Sample restaurant record with Nigerian and continental menus, private dining rooms and space for large groups.",
    services: ["Nigerian & continental menu", "Private dining room", "Group bookings", "Outdoor seating", "Vegetarian options"],
    tags: ["restaurant", "food", "eat", "family", "gathering", "dinner", "celebration", "group", "date"],
    hours: H("Every day 11:00–23:00", 11, 23),
    phone: null,
    website: null,
    rating: { value: 4.4, count: 402, source: "Sample review dataset" },
    priceLevel: 3,
    accessibility: ["Step-free entrance", "Accessible toilets"],
    emergency: false,
  },
  {
    name: "National Heritage Museum (sample)",
    category: "cultural",
    subtype: "Museum",
    ownership: "Public",
    locationSlug: "wuse-2-abuja",
    area: "Central Area",
    address: "Central Business District, Abuja",
    coords: [9.0574, 7.4899],
    description:
      "Sample museum record covering regional history, crafts and archive exhibitions with guided tours.",
    services: ["Permanent history exhibition", "Guided tours", "School visits", "Archive room", "Gift shop"],
    tags: ["museum", "history", "culture", "heritage", "learn", "tourist", "sightseeing", "holiday", "school"],
    hours: H("Tue–Sun 09:00–17:00", 9, 17, [0, 2, 3, 4, 5, 6]),
    phone: null,
    website: null,
    rating: { value: 4.2, count: 96, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Ramp access", "Guided tour for visually impaired visitors"],
    emergency: false,
  },
  {
    name: "Wuse Model Secondary School (sample)",
    category: "education",
    subtype: "Secondary school",
    ownership: "Public",
    locationSlug: "wuse-2-abuja",
    area: "Wuse 2",
    address: "Wuse Zone 5, Abuja",
    coords: [9.0642, 7.4741],
    description: "Sample secondary school record with science and arts streams and an examination centre.",
    services: ["Junior secondary", "Senior secondary", "Science laboratories", "Examination centre"],
    tags: ["school", "education", "secondary", "children", "study", "learn", "admission"],
    hours: H("Mon–Fri 07:30–15:30", 7, 15, [1, 2, 3, 4, 5]),
    phone: null,
    website: null,
    rating: null,
    priceLevel: 1,
    accessibility: ["Ground-floor classrooms"],
    emergency: false,
  },
  {
    name: "Wuse Central Bus Terminal (sample)",
    category: "transportation",
    subtype: "Bus terminal",
    ownership: "Public",
    locationSlug: "wuse-2-abuja",
    area: "Wuse 2",
    address: "Wuse Market Road, Abuja",
    coords: [9.0712, 7.4593],
    description: "Sample intercity and city bus terminal record with scheduled departures and taxi ranks.",
    services: ["Intercity coaches", "City buses", "Taxi rank", "Ticket office", "Luggage handling"],
    tags: ["bus", "transport", "travel", "terminal", "station", "journey", "commute"],
    hours: H("Every day 05:00–22:00", 5, 22),
    phone: null,
    website: null,
    rating: { value: 3.7, count: 143, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Step-free platform"],
    emergency: false,
  },

  // --------------------------------------------------------- Sabon Gari, Kano
  {
    name: "Sabon Gari General Hospital (sample)",
    category: "healthcare",
    subtype: "General hospital",
    ownership: "Public",
    locationSlug: "sabon-gari-kano",
    area: "Sabon Gari",
    address: "Church Road, Sabon Gari, Kano",
    coords: [12.0041, 8.5876],
    description:
      "Sample general hospital record with 24-hour emergency cover, outpatient clinics and a maternity wing.",
    services: ["Accident & emergency", "General outpatient", "Maternity", "Malaria & fever testing", "Pharmacy"],
    tags: ["hospital", "malaria", "fever", "treatment", "emergency", "sick", "doctor", "maternity"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: { value: 3.9, count: 88, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Step-free entrance"],
    emergency: true,
  },
  {
    name: "Sabon Gari Primary Health Centre (sample)",
    category: "healthcare",
    subtype: "Primary healthcare centre",
    ownership: "Public",
    locationSlug: "sabon-gari-kano",
    area: "Sabon Gari",
    address: "Ibo Road, Sabon Gari, Kano",
    coords: [11.9987, 8.5951],
    description: "Sample primary healthcare centre record for routine care, immunisation and antenatal visits.",
    services: ["Immunisation", "Antenatal care", "Malaria testing", "Routine consultation"],
    tags: ["clinic", "primary health", "malaria", "children", "immunisation", "antenatal", "treatment"],
    hours: H("Mon–Sat 08:00–17:00", 8, 17, MON_SAT),
    phone: null,
    website: null,
    rating: { value: 3.8, count: 41, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Step-free entrance"],
    emergency: false,
  },
  {
    name: "Sabon Gari Market (sample)",
    category: "shopping",
    subtype: "Open market",
    ownership: "Public",
    locationSlug: "sabon-gari-kano",
    area: "Sabon Gari",
    address: "Sabon Gari Market Road, Kano",
    coords: [12.0009, 8.5903],
    description: "Sample market record — a large trading area for textiles, food produce and household goods.",
    services: ["Food produce", "Textiles", "Household goods", "Wholesale trading"],
    tags: ["market", "shopping", "buy", "trade", "business", "goods", "food"],
    hours: H("Mon–Sat 07:00–19:00", 7, 19, MON_SAT),
    phone: null,
    website: null,
    rating: { value: 4.0, count: 221, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Uneven surfaces in parts of the market"],
    emergency: false,
  },
  {
    name: "Kano City Heritage Walls (sample)",
    category: "cultural",
    subtype: "Historic site",
    ownership: "Public",
    locationSlug: "sabon-gari-kano",
    area: "Kano City",
    address: "Old City, Kano",
    coords: [11.9908, 8.5169],
    description: "Sample heritage site record covering the historic city walls and gates with guided walks.",
    services: ["Guided heritage walk", "History exhibition", "Photography viewpoints"],
    tags: ["history", "heritage", "culture", "tourist", "sightseeing", "learn", "holiday", "walk"],
    hours: H("Every day 08:00–18:00", 8, 18),
    phone: null,
    website: null,
    rating: { value: 4.3, count: 134, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Uneven ground"],
    emergency: false,
  },
  {
    name: "Sabon Gari Fire Service Station (sample)",
    category: "emergency",
    subtype: "Fire station",
    ownership: "Public",
    locationSlug: "sabon-gari-kano",
    area: "Sabon Gari",
    address: "Airport Road, Kano",
    coords: [12.0068, 8.5822],
    description: "Sample fire service record providing 24-hour fire and rescue response.",
    services: ["Fire response", "Rescue services", "Safety inspection"],
    tags: ["fire", "emergency", "rescue", "safety", "help"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: null,
    priceLevel: null,
    accessibility: [],
    emergency: true,
  },
  {
    name: "Northern Grill House (sample)",
    category: "restaurant",
    subtype: "Restaurant",
    ownership: "Private",
    locationSlug: "sabon-gari-kano",
    area: "Sabon Gari",
    address: "France Road, Sabon Gari, Kano",
    coords: [12.0031, 8.5934],
    description: "Sample restaurant record serving northern Nigerian grills with family seating areas.",
    services: ["Grilled dishes", "Family seating", "Takeaway", "Group bookings"],
    tags: ["restaurant", "food", "eat", "family", "gathering", "dinner", "group"],
    hours: H("Every day 11:00–22:00", 11, 22),
    phone: null,
    website: null,
    rating: { value: 4.1, count: 167, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Step-free entrance"],
    emergency: false,
  },
  {
    name: "Kano Technical College (sample)",
    category: "education",
    subtype: "Technical college",
    ownership: "Public",
    locationSlug: "sabon-gari-kano",
    area: "Kano",
    address: "Zaria Road, Kano",
    coords: [11.9847, 8.5411],
    description: "Sample technical and vocational college record offering trade and engineering programmes.",
    services: ["Engineering diplomas", "Vocational trades", "Evening classes", "Apprenticeships"],
    tags: ["college", "education", "training", "vocational", "skills", "learn", "study"],
    hours: H("Mon–Fri 08:00–17:00", 8, 17, [1, 2, 3, 4, 5]),
    phone: null,
    website: null,
    rating: null,
    priceLevel: 1,
    accessibility: ["Ramp access to main block"],
    emergency: false,
  },

  // ------------------------------------------------------------- Ikeja, Lagos
  {
    name: "Ikeja Teaching Hospital (sample)",
    category: "healthcare",
    subtype: "Teaching hospital",
    ownership: "Public",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Oba Akran Avenue, Ikeja, Lagos",
    coords: [6.6047, 3.3419],
    description:
      "Sample teaching hospital record with specialist departments, a 24-hour emergency unit and diagnostic imaging.",
    services: ["Accident & emergency", "Specialist clinics", "Imaging & diagnostics", "Infectious disease unit", "Malaria & fever testing", "Surgery"],
    tags: ["hospital", "specialist", "malaria", "fever", "treatment", "emergency", "surgery", "sick", "referral"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: { value: 4.2, count: 356, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Step-free entrance", "Wheelchairs available", "Accessible toilets"],
    emergency: true,
  },
  {
    name: "Allen Avenue Medical Centre (sample)",
    category: "healthcare",
    subtype: "Private hospital",
    ownership: "Private",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Allen Avenue, Ikeja, Lagos",
    coords: [6.5972, 3.3521],
    description: "Sample private hospital record with outpatient clinics, laboratory and short-stay beds.",
    services: ["General outpatient", "Laboratory", "Short-stay beds", "Paediatrics", "Malaria treatment"],
    tags: ["hospital", "clinic", "malaria", "children", "treatment", "paediatrics", "sick"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: { value: 4.5, count: 212, source: "Sample review dataset" },
    priceLevel: 4,
    accessibility: ["Lift access", "Accessible parking"],
    emergency: true,
  },
  {
    name: "Ikeja City Pharmacy (sample)",
    category: "pharmacy",
    subtype: "Retail pharmacy",
    ownership: "Private",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Obafemi Awolowo Way, Ikeja, Lagos",
    coords: [6.6012, 3.3487],
    description: "Sample pharmacy record with extended evening hours and prescription dispensing.",
    services: ["Prescription dispensing", "Over-the-counter medicines", "Anti-malarials", "Baby care products"],
    tags: ["pharmacy", "chemist", "medicine", "drugs", "prescription", "malaria", "nearby"],
    hours: H("Every day 08:00–23:00", 8, 23),
    phone: null,
    website: null,
    rating: { value: 4.3, count: 98, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Step-free entrance"],
    emergency: false,
  },
  {
    name: "Ikeja Recreation Park (sample)",
    category: "outdoor",
    subtype: "Recreation park",
    ownership: "Public",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Alausa, Ikeja, Lagos",
    coords: [6.6135, 3.3585],
    description: "Sample park record with lawns, a jogging loop, a lake view and quiet seating areas.",
    services: ["Jogging loop", "Lakeside seating", "Children's playground", "Picnic areas", "Weekend markets"],
    tags: ["park", "relax", "peaceful", "quiet", "holiday", "family", "children", "outdoor", "weekend", "jogging", "nature"],
    hours: H("Every day 06:00–19:00", 6, 19),
    phone: null,
    website: null,
    rating: { value: 4.4, count: 288, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Paved paths", "Accessible toilets"],
    emergency: false,
  },
  {
    name: "Lagos Family Cinema Complex (sample)",
    category: "entertainment",
    subtype: "Cinema & games",
    ownership: "Private",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Ikeja GRA, Lagos",
    coords: [6.5893, 3.3502],
    description: "Sample entertainment complex record with cinema screens, bowling and a children's arcade.",
    services: ["Cinema screens", "Bowling", "Children's arcade", "Food court", "Birthday packages"],
    tags: ["entertainment", "cinema", "children", "kids", "family", "holiday", "fun", "weekend", "games"],
    hours: H("Every day 10:00–23:00", 10, 23),
    phone: null,
    website: null,
    rating: { value: 4.5, count: 512, source: "Sample review dataset" },
    priceLevel: 3,
    accessibility: ["Lift access", "Wheelchair spaces in screens"],
    emergency: false,
  },
  {
    name: "Ikeja Garden Restaurant (sample)",
    category: "restaurant",
    subtype: "Garden restaurant",
    ownership: "Private",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Isaac John Street, Ikeja GRA, Lagos",
    coords: [6.5921, 3.3546],
    description: "Sample restaurant record with a garden terrace, event space and family menus.",
    services: ["Garden terrace", "Event space for 60 guests", "Family menu", "Vegetarian options", "Reservations"],
    tags: ["restaurant", "food", "family", "gathering", "celebration", "group", "event", "dinner"],
    hours: H("Every day 12:00–23:00", 12, 23),
    phone: null,
    website: null,
    rating: { value: 4.6, count: 634, source: "Sample review dataset" },
    priceLevel: 3,
    accessibility: ["Step-free entrance", "Accessible toilets"],
    emergency: false,
  },
  {
    name: "Murtala Muhammed Airport (sample record)",
    category: "transportation",
    subtype: "International airport",
    ownership: "Public",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Airport Road, Ikeja, Lagos",
    coords: [6.5774, 3.3212],
    description: "Sample airport record with domestic and international terminals and ground transport links.",
    services: ["Domestic terminal", "International terminal", "Car hire", "Taxi rank", "Long-stay parking"],
    tags: ["airport", "flight", "travel", "transport", "journey", "hub"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: { value: 3.6, count: 1204, source: "Sample review dataset" },
    priceLevel: null,
    accessibility: ["Step-free access", "Assistance service"],
    emergency: false,
  },
  {
    name: "Ikeja Divisional Police Headquarters (sample)",
    category: "emergency",
    subtype: "Police station",
    ownership: "Public",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Oba Akinjobi Way, Ikeja GRA, Lagos",
    coords: [6.5958, 3.3563],
    description: "Sample police headquarters record with 24-hour reporting desk and patrol coordination.",
    services: ["Incident reporting", "Patrol response", "Emergency coordination"],
    tags: ["police", "emergency", "safety", "report", "help", "crime"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: null,
    priceLevel: null,
    accessibility: ["Step-free entrance"],
    emergency: true,
  },
  {
    name: "Lagos State University Campus (sample)",
    category: "education",
    subtype: "University campus",
    ownership: "Public",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Ikeja, Lagos",
    coords: [6.6081, 3.3628],
    description: "Sample university campus record offering undergraduate and postgraduate programmes.",
    services: ["Undergraduate programmes", "Postgraduate programmes", "Library", "Research centres"],
    tags: ["university", "education", "degree", "study", "learn", "admission", "research"],
    hours: H("Mon–Fri 08:00–18:00", 8, 18, [1, 2, 3, 4, 5]),
    phone: null,
    website: null,
    rating: { value: 4.0, count: 173, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Ramp access", "Accessible library"],
    emergency: false,
  },
  {
    name: "Ikeja Business Hub (sample)",
    category: "business",
    subtype: "Co-working & business services",
    ownership: "Private",
    locationSlug: "ikeja-lagos",
    area: "Ikeja",
    address: "Allen Avenue, Ikeja, Lagos",
    coords: [6.5989, 3.3499],
    description: "Sample business centre record with co-working desks, meeting rooms and registration support.",
    services: ["Co-working desks", "Meeting rooms", "Business registration support", "Printing", "High-speed internet"],
    tags: ["business", "work", "office", "meeting", "startup", "coworking", "invest"],
    hours: H("Mon–Sat 08:00–20:00", 8, 20, MON_SAT),
    phone: null,
    website: null,
    rating: { value: 4.4, count: 87, source: "Sample review dataset" },
    priceLevel: 3,
    accessibility: ["Lift access"],
    emergency: false,
  },

  // -------------------------------------------------------------------- Enugu
  {
    name: "Enugu State Teaching Hospital (sample)",
    category: "healthcare",
    subtype: "Teaching hospital",
    ownership: "Public",
    locationSlug: "enugu",
    area: "Enugu",
    address: "Ogui Road, Enugu",
    coords: [6.4471, 7.4986],
    description: "Sample teaching hospital record with specialist units and a 24-hour emergency department.",
    services: ["Accident & emergency", "Specialist clinics", "Laboratory", "Malaria & fever testing", "Surgery"],
    tags: ["hospital", "specialist", "malaria", "treatment", "emergency", "sick", "referral"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: { value: 4.0, count: 145, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Step-free entrance", "Wheelchairs available"],
    emergency: true,
  },
  {
    name: "Enugu Hillside Clinic (sample)",
    category: "healthcare",
    subtype: "Private clinic",
    ownership: "Private",
    locationSlug: "enugu",
    area: "Enugu",
    address: "Independence Layout, Enugu",
    coords: [6.4392, 7.5233],
    description: "Sample clinic record for general consultations, fever screening and family medicine.",
    services: ["General consultation", "Fever screening", "Family medicine", "Laboratory tests"],
    tags: ["clinic", "malaria", "fever", "treatment", "family", "consultation"],
    hours: H("Mon–Sat 08:00–19:00", 8, 19, MON_SAT),
    phone: null,
    website: null,
    rating: { value: 4.2, count: 63, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Step-free entrance"],
    emergency: false,
  },
  {
    name: "Enugu Hilltop Nature Reserve (sample)",
    category: "outdoor",
    subtype: "Nature reserve",
    ownership: "Public",
    locationSlug: "enugu",
    area: "Enugu",
    address: "Milliken Hill, Enugu",
    coords: [6.4703, 7.4791],
    description: "Sample nature reserve record with hillside walking trails, viewpoints and quiet picnic spots.",
    services: ["Walking trails", "Scenic viewpoints", "Picnic areas", "Guided nature walks"],
    tags: ["nature", "relax", "peaceful", "quiet", "outdoor", "hiking", "holiday", "sightseeing", "weekend", "fresh air"],
    hours: H("Every day 07:00–18:00", 7, 18),
    phone: null,
    website: null,
    rating: { value: 4.6, count: 176, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Steep trails — limited wheelchair access"],
    emergency: false,
  },
  {
    name: "Enugu Coal Heritage Centre (sample)",
    category: "cultural",
    subtype: "Heritage centre",
    ownership: "Public",
    locationSlug: "enugu",
    area: "Enugu",
    address: "Coal Camp, Enugu",
    coords: [6.4408, 7.4869],
    description: "Sample heritage centre record telling the mining history of the area through exhibits and tours.",
    services: ["History exhibition", "Guided tours", "School programmes", "Archive collection"],
    tags: ["history", "heritage", "culture", "learn", "tourist", "sightseeing", "school", "holiday"],
    hours: H("Tue–Sun 09:00–17:00", 9, 17, [0, 2, 3, 4, 5, 6]),
    phone: null,
    website: null,
    rating: { value: 4.1, count: 74, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Ramp access"],
    emergency: false,
  },
  {
    name: "Enugu Family Kitchen (sample)",
    category: "restaurant",
    subtype: "Family restaurant",
    ownership: "Private",
    locationSlug: "enugu",
    area: "Enugu",
    address: "Zik Avenue, Enugu",
    coords: [6.4438, 7.4923],
    description: "Sample restaurant record with local dishes, family tables and a small event room.",
    services: ["Local dishes", "Family tables", "Event room", "Takeaway"],
    tags: ["restaurant", "food", "family", "gathering", "group", "dinner", "celebration"],
    hours: H("Every day 10:00–22:00", 10, 22),
    phone: null,
    website: null,
    rating: { value: 4.3, count: 158, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Step-free entrance"],
    emergency: false,
  },
  {
    name: "Enugu Central Police Station (sample)",
    category: "emergency",
    subtype: "Police station",
    ownership: "Public",
    locationSlug: "enugu",
    area: "Enugu",
    address: "Ogui Road, Enugu",
    coords: [6.4459, 7.4951],
    description: "Sample police station record with 24-hour reporting and emergency response coordination.",
    services: ["Incident reporting", "Emergency response", "Community policing"],
    tags: ["police", "emergency", "safety", "report", "help"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: null,
    priceLevel: null,
    accessibility: ["Step-free entrance"],
    emergency: true,
  },
  {
    name: "Enugu State Secretariat (sample)",
    category: "government",
    subtype: "Government office",
    ownership: "Public",
    locationSlug: "enugu",
    area: "Enugu",
    address: "Independence Layout, Enugu",
    coords: [6.4351, 7.5178],
    description: "Sample government office record handling civil registration, permits and public enquiries.",
    services: ["Civil registration", "Permits & licences", "Public enquiries", "Tax office"],
    tags: ["government", "permit", "licence", "registration", "documents", "official", "certificate"],
    hours: H("Mon–Fri 08:00–16:00", 8, 16, [1, 2, 3, 4, 5]),
    phone: null,
    website: null,
    rating: null,
    priceLevel: null,
    accessibility: ["Ramp access", "Ground-floor service desk"],
    emergency: false,
  },

  // ------------------------------------------------------------ Port Harcourt
  {
    name: "Port Harcourt General Hospital (sample)",
    category: "healthcare",
    subtype: "General hospital",
    ownership: "Public",
    locationSlug: "port-harcourt",
    area: "Port Harcourt",
    address: "Harbour Road, Port Harcourt",
    coords: [4.8127, 7.0432],
    description: "Sample general hospital record with emergency cover, outpatient clinics and diagnostics.",
    services: ["Accident & emergency", "General outpatient", "Diagnostics", "Malaria & fever testing", "Maternity"],
    tags: ["hospital", "malaria", "fever", "treatment", "emergency", "sick", "doctor"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: { value: 3.9, count: 121, source: "Sample review dataset" },
    priceLevel: 2,
    accessibility: ["Step-free entrance"],
    emergency: true,
  },
  {
    name: "Rivers Specialist Clinic (sample)",
    category: "healthcare",
    subtype: "Specialist clinic",
    ownership: "Private",
    locationSlug: "port-harcourt",
    area: "GRA Phase 2",
    address: "Aba Road, Port Harcourt",
    coords: [4.8221, 7.0357],
    description: "Sample specialist clinic record covering internal medicine, cardiology and tropical disease clinics.",
    services: ["Internal medicine", "Cardiology", "Tropical disease clinic", "Laboratory", "Health screening"],
    tags: ["clinic", "specialist", "treatment", "malaria", "screening", "consultation"],
    hours: H("Mon–Sat 08:00–18:00", 8, 18, MON_SAT),
    phone: null,
    website: null,
    rating: { value: 4.5, count: 94, source: "Sample review dataset" },
    priceLevel: 4,
    accessibility: ["Lift access", "Accessible parking"],
    emergency: false,
  },
  {
    name: "Waterfront Leisure Park (sample)",
    category: "recreation",
    subtype: "Waterfront park",
    ownership: "Public",
    locationSlug: "port-harcourt",
    area: "Port Harcourt",
    address: "Waterlines, Port Harcourt",
    coords: [4.8062, 7.0293],
    description: "Sample waterfront park record with promenades, boat viewing points and family picnic lawns.",
    services: ["Waterfront promenade", "Picnic lawns", "Children's playground", "Boat viewing point", "Kiosks"],
    tags: ["park", "relax", "peaceful", "holiday", "family", "children", "weekend", "outdoor", "water", "sightseeing"],
    hours: H("Every day 07:00–20:00", 7, 20),
    phone: null,
    website: null,
    rating: { value: 4.2, count: 203, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Paved promenade", "Accessible toilets"],
    emergency: false,
  },
  {
    name: "Rivers Cultural Centre (sample)",
    category: "cultural",
    subtype: "Cultural centre",
    ownership: "Public",
    locationSlug: "port-harcourt",
    area: "Port Harcourt",
    address: "Moscow Road, Port Harcourt",
    coords: [4.8104, 7.0261],
    description: "Sample cultural centre record hosting exhibitions, local history displays and performances.",
    services: ["Exhibitions", "Local history displays", "Performances", "Craft workshops"],
    tags: ["culture", "history", "heritage", "learn", "tourist", "holiday", "entertainment", "sightseeing"],
    hours: H("Tue–Sun 10:00–18:00", 10, 18, [0, 2, 3, 4, 5, 6]),
    phone: null,
    website: null,
    rating: { value: 4.1, count: 89, source: "Sample review dataset" },
    priceLevel: 1,
    accessibility: ["Ramp access", "Accessible seating"],
    emergency: false,
  },
  {
    name: "Harbour View Family Restaurant (sample)",
    category: "restaurant",
    subtype: "Family restaurant",
    ownership: "Private",
    locationSlug: "port-harcourt",
    area: "Port Harcourt",
    address: "Olu Obasanjo Road, Port Harcourt",
    coords: [4.8089, 7.0338],
    description: "Sample restaurant record with river views, family seating and a private function room.",
    services: ["Seafood & local dishes", "Private function room", "Family seating", "Reservations"],
    tags: ["restaurant", "food", "family", "gathering", "group", "celebration", "dinner"],
    hours: H("Every day 11:00–23:00", 11, 23),
    phone: null,
    website: null,
    rating: { value: 4.4, count: 246, source: "Sample review dataset" },
    priceLevel: 3,
    accessibility: ["Step-free entrance"],
    emergency: false,
  },
  {
    name: "Port Harcourt Emergency Medical Base (sample)",
    category: "emergency",
    subtype: "Ambulance & emergency medical service",
    ownership: "Public",
    locationSlug: "port-harcourt",
    area: "Port Harcourt",
    address: "Ikwerre Road, Port Harcourt",
    coords: [4.8203, 7.0206],
    description: "Sample emergency medical service record coordinating ambulance dispatch across the city.",
    services: ["Ambulance dispatch", "Emergency first response", "Inter-hospital transfer"],
    tags: ["ambulance", "emergency", "urgent", "medical", "help", "accident"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: null,
    priceLevel: null,
    accessibility: [],
    emergency: true,
  },
  {
    name: "Port Harcourt Riverside Hotel (sample)",
    category: "accommodation",
    subtype: "Hotel",
    ownership: "Private",
    locationSlug: "port-harcourt",
    area: "Port Harcourt",
    address: "Trans Amadi, Port Harcourt",
    coords: [4.8018, 7.0451],
    description: "Sample hotel record with family rooms, conference facilities and an on-site restaurant.",
    services: ["Family rooms", "Conference rooms", "Restaurant", "Airport shuttle", "Parking"],
    tags: ["hotel", "stay", "accommodation", "holiday", "family", "travel", "conference"],
    hours: ALWAYS,
    phone: null,
    website: null,
    rating: { value: 4.2, count: 311, source: "Sample review dataset" },
    priceLevel: 3,
    accessibility: ["Lift access", "Accessible rooms"],
    emergency: false,
  },
  {
    name: "Port Harcourt Central Mosque & Community Hall (sample)",
    category: "religious",
    subtype: "Place of worship",
    ownership: "Community",
    locationSlug: "port-harcourt",
    area: "Port Harcourt",
    address: "Creek Road, Port Harcourt",
    coords: [4.8137, 7.0187],
    description: "Sample place-of-worship record with daily prayers and a community hall for gatherings.",
    services: ["Daily prayers", "Community hall", "Community outreach"],
    tags: ["religious", "worship", "prayer", "quiet", "community", "peaceful"],
    hours: H("Every day 05:00–21:00", 5, 21),
    phone: null,
    website: null,
    rating: null,
    priceLevel: null,
    accessibility: ["Step-free entrance"],
    emergency: false,
  },
];

export const PLACES: Place[] = build(SEEDS);

export function placesForLocation(slug: string): Place[] {
  return PLACES.filter((p) => p.locationSlug === slug);
}

export function isOpenNow(hours: OpeningHours, now = new Date()): boolean | null {
  if (hours.opens === null && hours.closes === null) return true;
  if (hours.opens === null || hours.closes === null) return null;
  if (!hours.days.includes(now.getDay())) return false;
  const h = now.getHours() + now.getMinutes() / 60;
  return h >= hours.opens && h < hours.closes;
}

export function priceLabel(level: Place["priceLevel"]): string {
  if (level === null) return "Price information unavailable";
  return ["Low cost", "Moderate", "Higher cost", "Premium"][level - 1] ?? "Unavailable";
}
