/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as HealthcareRouteImport } from './routes/healthcare'
import { Route as HelpRouteImport } from './routes/help'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as LocationSlugRouteImport } from './routes/location.$slug'
import { Route as InsightSlugCategoryRouteImport } from './routes/insight.$slug.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcareRoute = HealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSlugRoute = LocationSlugRouteImport.update({
  id: '/location/$slug',
  path: '/location/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightSlugCategoryRoute = InsightSlugCategoryRouteImport.update({
  id: '/insight/$slug/$category',
  path: '/insight/$slug/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/compare': typeof CompareRoute
  '/discover': typeof DiscoverRoute
  '/emergency': typeof EmergencyRoute
  '/government': typeof GovernmentRoute
  '/healthcare': typeof HealthcareRoute
  '/help': typeof HelpRoute
  '/saved': typeof SavedRoute
  '/location/$slug': typeof LocationSlugRoute
  '/insight/$slug/$category': typeof InsightSlugCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/compare': typeof CompareRoute
  '/discover': typeof DiscoverRoute
  '/emergency': typeof EmergencyRoute
  '/government': typeof GovernmentRoute
  '/healthcare': typeof HealthcareRoute
  '/help': typeof HelpRoute
  '/saved': typeof SavedRoute
  '/location/$slug': typeof LocationSlugRoute
  '/insight/$slug/$category': typeof InsightSlugCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/business': typeof BusinessRoute
  '/compare': typeof CompareRoute
  '/discover': typeof DiscoverRoute
  '/emergency': typeof EmergencyRoute
  '/government': typeof GovernmentRoute
  '/healthcare': typeof HealthcareRoute
  '/help': typeof HelpRoute
  '/saved': typeof SavedRoute
  '/location/$slug': typeof LocationSlugRoute
  '/insight/$slug/$category': typeof InsightSlugCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/business'
    | '/compare'
    | '/discover'
    | '/emergency'
    | '/government'
    | '/healthcare'
    | '/help'
    | '/saved'
    | '/location/$slug'
    | '/insight/$slug/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/business'
    | '/compare'
    | '/discover'
    | '/emergency'
    | '/government'
    | '/healthcare'
    | '/help'
    | '/saved'
    | '/location/$slug'
    | '/insight/$slug/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/alerts'
    | '/auth'
    | '/business'
    | '/compare'
    | '/discover'
    | '/emergency'
    | '/government'
    | '/healthcare'
    | '/help'
    | '/saved'
    | '/location/$slug'
    | '/insight/$slug/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  BusinessRoute: typeof BusinessRoute
  CompareRoute: typeof CompareRoute
  DiscoverRoute: typeof DiscoverRoute
  EmergencyRoute: typeof EmergencyRoute
  GovernmentRoute: typeof GovernmentRoute
  HealthcareRoute: typeof HealthcareRoute
  HelpRoute: typeof HelpRoute
  SavedRoute: typeof SavedRoute
  LocationSlugRoute: typeof LocationSlugRoute
  InsightSlugCategoryRoute: typeof InsightSlugCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare': {
      id: '/healthcare'
      path: '/healthcare'
      fullPath: '/healthcare'
      preLoaderRoute: typeof HealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$slug': {
      id: '/location/$slug'
      path: '/location/$slug'
      fullPath: '/location/$slug'
      preLoaderRoute: typeof LocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight/$slug/$category': {
      id: '/insight/$slug/$category'
      path: '/insight/$slug/$category'
      fullPath: '/insight/$slug/$category'
      preLoaderRoute: typeof InsightSlugCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  BusinessRoute: BusinessRoute,
  CompareRoute: CompareRoute,
  DiscoverRoute: DiscoverRoute,
  EmergencyRoute: EmergencyRoute,
  GovernmentRoute: GovernmentRoute,
  HealthcareRoute: HealthcareRoute,
  HelpRoute: HelpRoute,
  SavedRoute: SavedRoute,
  LocationSlugRoute: LocationSlugRoute,
  InsightSlugCategoryRoute: InsightSlugCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
